FROM python:3.11

WORKDIR /app

RUN apt-get update && apt-get install -y \
    ffmpeg \
    git \
    curl \
    && rm -rf /var/lib/apt/lists/*

COPY docker3/omnivoice/requirements.omnivoice.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt --extra-index-url https://download.pytorch.org/whl/cu128 && pip cache purge

COPY docker3/omnivoice/server_omnivoice.py /app/server.py

ENV MODEL_PATH=/models/OmniVoice
ENV DEVICE=cuda

EXPOSE 8200

CMD ["python", "server.py"]
